# --- !Ups

CREATE TABLE USERS (
  ID varchar(36) NOT NULL,
  EMAIL varchar NOT NULL,
  FIRST_NAME varchar NOT NULL,
  LAST_NAME varchar NOT NULL,
  BUSINESS_ID UUID,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

-- A User can have multiple passwords with with different hasing algorithms
CREATE TABLE LOGIN_INFO (
  ID BIGSERIAL PRIMARY KEY,
  PROVIDER_ID VARCHAR NOT NULL,
  PROVIDER_KEY VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Mapping table between USER and LOGIN_INFO
CREATE TABLE USER_LOGIN_INFO (
  USER_ID VARCHAR NOT NULL REFERENCES  USERS(ID),
  LOGIN_INFO_ID BIGINT NOT NULL REFERENCES  LOGIN_INFO(ID),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Credentials based login info
CREATE TABLE PASSWORD_INFO (
  HASHER VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL,
  SALT VARCHAR,
  LOGIN_INFO_ID BIGINT NOT NULL REFERENCES  LOGIN_INFO(ID),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

# --- !Downs

DROP TABLE IF EXISTS PASSWORD_INFO;
DROP TABLE IF EXISTS USER_LOGIN_INFO;
DROP TABLE IF EXISTS LOGIN_INFO;
DROP TABLE IF EXISTS USERS;
