version: "3"

services:
  api:
    build:
      context: .
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db/postgres
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
    stdin_open: true

  db:
    image: postgres:10