POST  http://localhost:9000/graphql HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary
X-Auth-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxLXo3TWRJNlJnU1RnampZVzV6WTJpYjlCTXRnd3d1MU54OVZEY2d3aFBKRncrOGVyZ3FrUWJsbU9DMllCejZMTUwrcTFCMWJmNFVtaGIwTGFreHFjbjVXNFwvUEw3UmJhdk03cFlOdEtCYlZkU1RyeVk9IiwiaXNzIjoicGxheS1zaWxob3VldHRlIiwiZXhwIjoxNTI5MDYyNzg2LCJpYXQiOjE1MjY0NzA3ODYsImp0aSI6IjFmYzQ1M2E5MmU1YzM1MjM1OWYxN2VjNzUxMGQyYWJkZGJhOTQ1ZWYyYTYwZTgyMDE2OTNmYjI4NGRlNjI0Y2EyNGU1ZTYwODgxZGM5ZjAxMzBkYzU2ODM4MGVlODIyNDAzNjFiNWIxZTZkYTVkNjcxODdmNTJjZGJmMmNiNjEwMDhjZjQ4YWZmN2NlOTU0ZjdmZDEwODk0OGMyNjBkMDc0MDk5ZDAwMzQ4YWZjYmIxZTMzNjEwM2JlOGFjNjE2NTAxMjI3MmYyMGI1Y2Y4NTllZGY5ZTE0ZTNlMTg2ZjBiMmU1MmQwNGZlYmVhMGE5YmI2ZDI2Y2ViYmJjNDc0NGQifQ.AdkvbMlzAPoFeo3jRtiayUSEVqxcoUrqjqOY8Wk8zyY

--boundary
Content-Disposition: form-data; name="testfile"; filename="image.jpg"
Content-Type: image/jpeg

< /Users/pulasthibandara/Downloads/car-image.jpg

--boundary
Content-Disposition: form-data; name="query";

mutation addImage {
  uploadVehicleImage(
    input: {
      payload: {
          listingId: "7ae0712a-4787-11e8-842f-0ed5f89f718b"
          image: "testfile"
      },
      clientMutationId: "1234"
    }
  ) {
    clientMutationId
    payload {
      fileId
      file {
        id
        properties {
          ... on ImageProperties {
            fileName
            size
            type
          }
        }
      }
    }
  }
}

--boundary--
Content-Disposition: form-data; name="variables";

{ "test": null }
###
